# Basic setup
#baseURL:        ''
baseURL:        'https://exercices-souris.netlify.app/'
languageCode:   'fr-FR'
title:          'Exercices souris'

# Commenter obligatoirement pour netlify. D'ou le npm run prod
#publishDir:     '/opt/lampp/htdocs/Public/public-souris'
summaryLength:  '30'

googleAnalytics: G-7626RXV4Y4

# Content setup
paginate:       6

# Parameter settings
params:
  home:         'img/IMG_20231104_152510w900.webp'
  happy:        'images/M-Face-7.svg'
  unhappy:      'images/glassy-smiley-bad.svg'

  author:       'Thierry Charriot'
  description:  'Application gratuite, site gratuit entrainement au maniement souris, personnes débutant en informatique , personnes agées. Clic gauche, double clic, copier coller, clic droit supprimer.' 
  email:        'mrthierrycharriot(signe bizarre)gmail.com'
  github:       'https://github.com/bibibricodeur'